// examples/react/PixInLinkImage.jsx
// React component example — PixInLink Image Generator
// Usage: <PixInLinkImage prompt="sunset" width={1200} height={630} alt="Sunset" />

import React from 'react';

export function PixInLinkImage({ prompt, width = 800, height = 400, bg = 'ffffff', fg = '000000', style = 'realistic', seed, format = 'webp', alt = '', className = '' }) {
  const params = new URLSearchParams({ prompt, style, format });
  if (seed) params.set('seed', seed.toString());

  const src = `https://pixinlink.ru/api/v1/${width}x${height}/${bg}/${fg}?${params.toString()}`;

  return (
    <img
      src={src}
      alt={alt || prompt}
      className={className}
      loading="lazy"
      style={{ maxWidth: '100%', height: 'auto', borderRadius: 8 }}
    />
  );
}

// Hook for generating og:image meta tag
export function useOpenGraphImage(prompt, width = 1200, height = 630) {
  return `https://pixinlink.ru/api/v1/${width}x${height}/ffffff/333333?prompt=${encodeURIComponent(prompt)}&style=illustration&format=webp`;
}

// examples/vue/PixInLinkImage.vue
<!-- Vue.js component example — PixInLink Image -->
<template>
  <img
    :src="imageUrl"
    :alt="alt || prompt"
    :class="className"
    loading="lazy"
    style="max-width: 100%; height: auto; border-radius: 8px"
  />
</template>

<script>
export default {
  name: 'PixInLinkImage',
  props: {
    prompt: { type: String, required: true },
    width: { type: Number, default: 800 },
    height: { type: Number, default: 400 },
    bg: { type: String, default: 'ffffff' },
    fg: { type: String, default: '000000' },
    style: { type: String, default: 'realistic' },
    seed: { type: Number, default: null },
    format: { type: String, default: 'webp' },
    alt: { type: String, default: '' },
    className: { type: String, default: '' },
  },
  computed: {
    imageUrl() {
      const params = new URLSearchParams({ prompt: this.prompt, style: this.style, format: this.format });
      if (this.seed) params.set('seed', this.seed.toString());
      return `https://pixinlink.ru/api/v1/${this.width}x${this.height}/${this.bg}/${this.fg}?${params}`;
    },
  },
};
</script>
